TheReaLState/Models/CreateAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace TheReaLState.Models
{
    public class CreateAccount
    {
        [Required]
        public string FullName { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Mobile { get; set; }
        [Required]
        public string Password { get; set; }
        [Required]
        public string RepeatPassword { get; set; }
        [Required]
        public string SecurityCOde { get; set; }
    }
}

TheReaLState/Controllers/SignUpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TheReaLState.Models;
using TheReaLState.Manager;

namespace TheReaLState.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(SignInModel Login)
        {
            SignInManager Obj = new SignInManager();
            int a = Obj.SignIn(Login);
            if (a == 1)
            {
                Session["IsLogedIn"] = true;
                return RedirectToAction("Homes", "AddProperty");
            }
            else
            {
                ViewBag.Message = "Username Or Password is inCoreect";
                return View();
            }
        }
        public ActionResult Logout()
        {
            Session["IsLogedIn"] = null;
            return RedirectToAction("Homes","Buy");
        }
        public ActionResult Login(SignInModel Login)
        {
            SignInManager Obj = new SignInManager();
            int a = Obj.SignIn(Login);
            if (a == 1)
            {
                Session["IsLogedIn"] = true;
                return RedirectToAction("Homes", "AddProperty");
            }
            else
            {
                ViewBag.Message = "Username Or Password is inCoreect";
                return RedirectToAction("Homes", "Buy");
            }
        }
        public ActionResult CreateAccount()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateAccount(SignInModel Login)
        {
            return View();
        }
    }
}

TheReaLState/Views/SignUp/CreateAccount.cshtml
@model TheReaLState.Models.CreateAccount
@{
    ViewBag.Title = "CreateAccount";
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>The ReaL State - Create Account</title>
    <!-- Custom fonts for this template-->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5"><img src="~/Content/LogoImages/Logo.JPG" alt="Logo.JPG" style="width:100%;height:100%"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            @using (Html.BeginForm(FormMethod.Post))
                            {
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        @Html.Label("Full Name")
                                        @Html.TextBoxFor(x => x.FullName, new { @class = "form-control form-control-user", id = "exampleFullName", placeholder = "Enter Full Name" })
                                        @Html.ValidationMessageFor(x => x.FullName)
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Enter Email (This iS yOur Username)")
                                    @Html.TextBoxFor(x => x.Email, new { @class = "form-control form-control-user", type = "email" ,id = "exampleInputEmail", placeholder = "Enter Email Address (eg: abc@yahoo.com)" })
                                    @Html.ValidationMessageFor(x => x.Email)
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        @Html.Label("Contact Number")
                                        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control form-control-user", id = "exampleInputmobile", placeholder = "Enter Mobile Number" })
                                        @Html.ValidationMessageFor(x => x.Mobile)
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        @Html.Label("Create Your Strong Password")
                                        @Html.PasswordFor(x => x.Password, new { @class = "form-control form-control-user", id = "exampleInputPassword", placeholder = "Enter Password" })
                                        @Html.ValidationMessageFor(x => x.RepeatPassword)
                                    </div>
                                    <div class="col-sm-6">
                                        @Html.Label("Repeat it")
                                        @Html.PasswordFor(x => x.RepeatPassword, new { @class = "form-control form-control-user", id = "exampleInputRepeatPassword", placeholder = "Repeat Password" })
                                        @Html.ValidationMessageFor(x => x.RepeatPassword)
                                    </div>
                                </div>
                                <label class="ErrorMsg">@ViewBag.Message</label>
                                <input type="submit" value="Register Account" class="btn btn-primary btn-user btn-block" />
                            }
                            <hr>
                            <div class="text-center">
                                @Html.ActionLink("Forgot Password?","","", null, new { @class = "text-center" })
                            </div>
                            <div class="text-center">
                                @Html.ActionLink("Already have an account? Login!", "SignIn", "SignUp", null, new { @class = "text-center" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>
</body>
</html>

TheReaLState/Views/SignUp/SignIn.cshtml
@model TheReaLState.Models.SignInModel
@{
    ViewBag.Title = "SignIn";
    Layout = "";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>The Real State - Login</title>
    <!-- Custom fonts for this template-->
    <link href="~/Content/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/Content/css/sb-admin-2.min.css" rel="stylesheet">
</head>
<body class="bg-gradient-primary">
    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6"><img src="~/Content/LogoImages/Logo.JPG" alt="Logo.JPG" style="width:100%;height:100%"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Login</h1>
                                    </div>
                                    @using (Html.BeginForm(FormMethod.Post))
                                    {
                                        <div class="form-group">
                                            @Html.Label("eg: abc@yahoo")
                                            <input type="email" name="Username" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            @Html.Label("Don't Share wiTh Anyone")
                                            <input type="password" name="Password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <br />
                                        </div>
                                        <label class="ErrorMsg">@ViewBag.Message</label>
                                        <input type="submit" value="Login" class="btn btn-primary btn-user btn-block" />
                                    }
                                    <div class="form-group">
                                    </div>
                                    <div class="text-center">
                                        @Html.ActionLink("Forgot Password?", "", "", null, new { @class = "text-center" })
                                    </div>
                                    <div class="form-group">
                                    </div>
                                    <div class="text-center">
                                        @Html.ActionLink("Create an Account!", "CreateAccount", "SignUp", null, new { @class = "text-center" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="~/Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Content/vendor/jquery-easing/jquery.easing.min.js"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/Content/js/sb-admin-2.min.js"></script>
</body>
</html>